### ISSUE TITLE
Documentation looks wrong to me - serious bug I think

### ISSUE THREAD

**Issue by ddirector51** [ravem/synology-pcloud-and-rclone#1]
The scariest part of any copy or sync command is getting the args in the wrong order, copying from the destination to the source, and therefore losing valuable data.  I think that is what you have in the documentation.
```

> 
> First case: you want to mirror ALL the content of the folder DATA that's in your pcloud storage IN your NAS.
> 
> Find in your NAS the location of the destination folder, it should be in /PATH/TO/NAME_OF_YOUR_VOLUME. Take a look under Storage manager or give a simple:
> 
> ls / 
> and check the volume name. Let's say it's /volume1/share/DATA, to sync you you shall launch:
> 
>>>>>   rclone --config="/var/rclone.conf" sync pcloud:DATA/ /volume1/share/DATA
> Second case: You want to sync ALL pcloud content IN your storage: the command is:
> 
>>>>>>  rclone sync --config="/var/rclone.conf" pcloud:/ /volume1/share/CloudSync/pcloud/
```

Aren't these commands backward?  going from pcloud to Synology NAS?

By the way, thanks for the project and the detailed instructions.  Look like just what I am looking for, but using the correct rclone commands.

**Comment by ravem** [comment]
Ouch, you're right.
I apologize for the mistake, I have corrected the example,  tomorrow I will check again since I'm on the phone right now.
Thanks for opening the issue.

**Comment by ddirector51** [comment]
you fixed one, but you had a mistake in both of your example rclone
commands.
You need to fix the other one as well.

BTW, you're welcome.  It is easy to make this mistake.  Nightmare material!

**Comment by ravem** [comment]
Yes I've noticed the other mistake, but I'll leave the issue opened until I've double checked on a larger screen.
Thanks again

**Comment by ravem** [comment]
fixed and deleted redundant example
